Server: # 服务配置
  RunMode: debug  # 设置 gin 的运行模式
  HttpPort: 8000  # 默认的 HTTP 监听端口
  ReadTimeout: 60  # 允许读取的最大持续时间
  WriteTimeout: 60  # 允许写入的最大持续时间
App: # 应用配置
  DefaultPageSize: 10  # 设置默认每页数量
  MaxPageSize: 100  # 所允许的最大每页数量
  DefaultContextTimeout: 60
  LogSavePath: storage/logs  # 默认的应用日志存储路径
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: public/uploads  # 上传文件的最终保存目录
  UploadServerUrl: http://127.0.0.1:8000/static  # 上传文件后的用于展示的文件服务地址
  UploadImageMaxSize: 5  # 上传文件所允许的最大空间大小（MB）
  UploadImageAllowExts:  # 上传文件所允许的文件后缀
    - .jpg
    - .jpeg
    - .png